import { makeStyles } from "@material-ui/core";
export default makeStyles((theme) => ({
  roundSales: {
    width: "100%",
    height: "auto",
    paddingTop: "50px",
    paddingBottom: "100px",
    backgroundColor: theme.palette.secondary.main,
  },
  mainBox: {
    width: "100%",
    height: 600,
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
  },
  boxLeft: {
    width: 395,
    height: 470,
    borderRadius: 20,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: "rgb(22, 23, 26)",
    position: "relative",
    "&::before": {
      content: '"pre-sale"',
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textTransform: "uppercase",
      fontSize: 18,
      width: 175,
      borderTopLeftRadius: 15,
      borderTopRightRadius: 15,
      height: 40,
      marginTop: -40,
      fontWeight: "bold",
      backgroundColor: "orange",
    },
  },
  boxTitle: {
    fontSize: 18,
    marginTop: 50,
    marginBottom: 25,
  },
  btnTxt: {
    width: 270,
    height: 60,
    borderRadius: 50,
    cursor: "pointer",
    border: "2px solid #e3e4e6",
    textTransform: "none",
    fontSize: 18,
    fontWeight: 700,
    marginBottom: 50,
  },
  proBox: {
    border: "2px solid gray",
    borderRadius: 100,
    width: 150,
    height: 150,
    marginTop: 30,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
}));
